from aiogram.types import InlineKeyboardMarkup,InlineKeyboardButton

menu = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='❓ Что это ?',callback_data='menu_1')
btn2 = InlineKeyboardButton(text='📝 Подписка',callback_data='menu_2')
btn3 = InlineKeyboardButton(text='📚 Учить',callback_data='menu_3')
btn4 = InlineKeyboardButton(text='✒️ Решать',callback_data='menu_4')
btn5 = InlineKeyboardButton(text='📖 Занятия',callback_data='menu_1_2')
btn6 = InlineKeyboardButton(text='☎️ Связаться ',callback_data='social')
btn7 = InlineKeyboardButton(text='📨 Подписаться на рассылку',callback_data='mailing')
menu.insert(btn1)
menu.insert(btn2)
menu.insert(btn3)
menu.insert(btn4)
menu.insert(btn5)
menu.insert(btn6)
menu.insert(btn7)

#~~~~~~~~~~~~~~~~~~~~

menu_1 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='🌟 Оформить подписку',callback_data='menu_1_1')
btn2 = InlineKeyboardButton(text='📆 Записаться на занятия',callback_data='menu_1_2')
btn3 = InlineKeyboardButton(text='◀️ Назад',callback_data='back_to_menu')
menu_1.insert(btn1)
menu_1.insert(btn2)
menu_1.insert(btn3)

swap = InlineKeyboardMarkup(row_width=2)
btn1 = InlineKeyboardButton(text='◀️',callback_data='back_img')
btn2 = InlineKeyboardButton(text='▶️',callback_data='next_img')
btn3 = InlineKeyboardButton(text='🎒 Назад',callback_data='back_to_menu')
swap.insert(btn1)
swap.insert(btn2)
swap.insert(btn3)

menu_1_2 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='🛍 Выбрать пакет услуг',callback_data='menu_1_2_1')
btn2 = InlineKeyboardButton(text='◀️ Назад',callback_data='back_to_menu_1')
menu_1_2.insert(btn1)
menu_1_2.insert(btn2)

menu_1_2_1 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='🌟 Премиум +1',callback_data='menu_1_2_1_1')
btn2 = InlineKeyboardButton(text='🌟 Премиум +2',callback_data='menu_1_2_1_2')
btn3 = InlineKeyboardButton(text='🌟 Премиум +4',callback_data='menu_1_2_1_2')
btn4 = InlineKeyboardButton(text='🌟 Премиум +8',callback_data='menu_1_2_1_3')
btn5 = InlineKeyboardButton(text='◀️ Назад',callback_data='back_to_menu_1_2')
menu_1_2_1.insert(btn1)
menu_1_2_1.insert(btn2)
menu_1_2_1.insert(btn3)
menu_1_2_1.insert(btn4)
menu_1_2_1.insert(btn5)

menu_2 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='⭐ Подписка супер',callback_data='menu_2_1')
btn2 = InlineKeyboardButton(text='🌟 Подписка премиум',callback_data='menu_2_2')
btn3 = InlineKeyboardButton(text='◀️ Назад',callback_data='back_to_menu_1')
menu_2.insert(btn1)
menu_2.insert(btn2)
menu_2.insert(btn3)


back = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='◀️ Назад',callback_data='back_to_menu')
back.insert(btn1)

menu_3 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='📕 Теория лексика',callback_data='menu_3_1')
btn2 = InlineKeyboardButton(text='📙 Теория морфологии',callback_data='menu_3_2')
btn3 = InlineKeyboardButton(text='📘 Теория орфографии',callback_data='menu_3_3')
btn4 = InlineKeyboardButton(text='📗 Теория синтаксиса',callback_data='menu_3_4')
btn5 = InlineKeyboardButton(text='📕 Теория пунктуации',callback_data='menu_3_5')
btn6 = InlineKeyboardButton(text='📗 Теория речевых заданий',callback_data='menu_3_6')
btn7 = InlineKeyboardButton(text='◀️ Назад',callback_data='back_to_menu')
menu_3.insert(btn1)
menu_3.insert(btn2)
menu_3.insert(btn3)
menu_3.insert(btn4)
menu_3.insert(btn5)
menu_3.insert(btn6)
menu_3.insert(btn7)

menu_3_1 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='📕 По темам',callback_data='menu_3_1_1')
btn2 = InlineKeyboardButton(text='📕 По заданиям',callback_data='menu_3_1_2')
btn3 = InlineKeyboardButton(text='◀️ Назад',callback_data='back_to_menu_3')
menu_3_1.insert(btn1)
menu_3_1.insert(btn2)
menu_3_1.insert(btn3)

menu_3_1_1 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='📙 Тема №1 Значение слов',callback_data='menu_3_1_1_1')
btn2 = InlineKeyboardButton(text='📙 Тема №2 Синонимы, Антонимы, Омонимы, Паронимы',callback_data='menu_3_1_1_2')
btn3 = InlineKeyboardButton(text='📙 Тема №3 Тавтология и Плеоназмы',callback_data='menu_3_1_1_3')
btn4 = InlineKeyboardButton(text='📙 Тема №4 Фразеологизмы',callback_data='menu_3_1_1_4')
btn5 = InlineKeyboardButton(text='◀️ Назад',callback_data='back_to_menu_3_1')
menu_3_1_1.insert(btn1)
menu_3_1_1.insert(btn2)
menu_3_1_1.insert(btn3)
menu_3_1_1.insert(btn4)
menu_3_1_1.insert(btn5)

menu_3_1_2 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='📘 №2 Значение слов',callback_data='menu_3_1_2_1')
btn2 = InlineKeyboardButton(text='📘 №5 Паронимы',callback_data='menu_3_1_2_2')
btn3 = InlineKeyboardButton(text='📘 №6 Тавтология и Плеоназмы',callback_data='menu_3_1_2_3')
btn4 = InlineKeyboardButton(text='📘 №25 Поиск слов в тексте',callback_data='menu_3_1_2_4')
btn5 = InlineKeyboardButton(text='◀️ Назад',callback_data='back_to_menu_3_1')
menu_3_1_2.insert(btn1)
menu_3_1_2.insert(btn2)
menu_3_1_2.insert(btn3)
menu_3_1_2.insert(btn4)
menu_3_1_2.insert(btn5)

menu_3_2 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='📗 Тема №1 Морфология, Морфемика, Части речи',callback_data='menu_3_2_1')
btn2 = InlineKeyboardButton(text='📗 Тема №2 Существительные',callback_data='menu_3_2_2')
btn3 = InlineKeyboardButton(text='📗 Тема №3 Прилагательный',callback_data='menu_3_2_3')
btn4 = InlineKeyboardButton(text='📗 Тема №4 Числительное',callback_data='menu_3_2_4')
btn5 = InlineKeyboardButton(text='📗 Тема №5 Местоимение',callback_data='menu_3_2_5')
btn6 = InlineKeyboardButton(text='📗 Тема №6 Глагол',callback_data='menu_3_2_6')
btn7 = InlineKeyboardButton(text='📗 Тема №7 Причастие',callback_data='menu_3_2_7')
btn8 = InlineKeyboardButton(text='📗 Тема №8 Наречие',callback_data='menu_3_2_8')
btn9 = InlineKeyboardButton(text='📗 Тема №9 Деепричастие',callback_data='menu_3_2_9')
btn10 = InlineKeyboardButton(text='📗 Тема №10 Служебные части речи',callback_data='menu_3_2_10')
btn11 = InlineKeyboardButton(text='📗 Тема №11 Предлог',callback_data='menu_3_2_11')
btn12 = InlineKeyboardButton(text='📗 Тема №12 Союз',callback_data='menu_3_2_12')
btn13 = InlineKeyboardButton(text='📗 Тема №13 Частицы',callback_data='menu_3_2_13')
btn14 = InlineKeyboardButton(text='📗 Какие повторить',callback_data='menu_3_2_14')
btn15 = InlineKeyboardButton(text='◀️ Назад',callback_data='back_to_menu_3')
menu_3_2.insert(btn1)
menu_3_2.insert(btn2)
menu_3_2.insert(btn3)
menu_3_2.insert(btn4)
menu_3_2.insert(btn5)
menu_3_2.insert(btn6)
menu_3_2.insert(btn7)
menu_3_2.insert(btn8)
menu_3_2.insert(btn9)
menu_3_2.insert(btn10)
menu_3_2.insert(btn11)
menu_3_2.insert(btn12)
menu_3_2.insert(btn13)
menu_3_2.insert(btn14)
menu_3_2.insert(btn15)

menu_3_3 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='📕 №1 Части речи',callback_data='menu_3_3_1')
btn2 = InlineKeyboardButton(text='📕 №7 Формы слова',callback_data='menu_3_3_2')
btn3 = InlineKeyboardButton(text='📕 №9 Корни',callback_data='menu_3_3_3')
btn4 = InlineKeyboardButton(text='📕 №10 Приставки',callback_data='menu_3_3_4')
btn5 = InlineKeyboardButton(text='📕 №11 Суффиксы',callback_data='menu_3_3_5')
btn6 = InlineKeyboardButton(text='📕 №12 Спряжения',callback_data='menu_3_3_6')
btn7 = InlineKeyboardButton(text='📕 №13 Не/Ни',callback_data='menu_3_3_7')
btn8 = InlineKeyboardButton(text='📕 №14 Слитное/Раздельное/Дефис',callback_data='menu_3_3_8')
btn9 = InlineKeyboardButton(text='📕 №15 Н И НН',callback_data='menu_3_3_9')
btn10 = InlineKeyboardButton(text='📕 №26 Поиск предложения в тексте',callback_data='menu_3_3_10')
btn11 = InlineKeyboardButton(text='📕 Какие повторить',callback_data='menu_3_3_11')
btn12 = InlineKeyboardButton(text='◀️ Назад',callback_data='back_to_menu_3')
menu_3_3.insert(btn1)
menu_3_3.insert(btn2)
menu_3_3.insert(btn3)
menu_3_3.insert(btn4)
menu_3_3.insert(btn5)
menu_3_3.insert(btn6)
menu_3_3.insert(btn7)
menu_3_3.insert(btn8)
menu_3_3.insert(btn9)
menu_3_3.insert(btn10)
menu_3_3.insert(btn11)
menu_3_3.insert(btn12)

menu_3_4 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='📙 Тема №1 Связи',callback_data='menu_3_4_1')
btn2 = InlineKeyboardButton(text='📙 Тема №2 Словосочетания',callback_data='menu_3_4_2')
btn3 = InlineKeyboardButton(text='📙 Тема №3 Главные члены предложения',callback_data='menu_3_4_3')
btn4 = InlineKeyboardButton(text='📙 Тема №4 Односоставные предложения',callback_data='menu_3_4_4')
btn5 = InlineKeyboardButton(text='📙 Тема №5 Второстепенные члены предложения',callback_data='menu_3_4_5')
btn6 = InlineKeyboardButton(text='📙 Тема №6 ССП',callback_data='menu_3_4_6')
btn7 = InlineKeyboardButton(text='📙 Тема №7 СПП',callback_data='menu_3_4_7')
btn8 = InlineKeyboardButton(text='📙 Тема №8 БСП',callback_data='menu_3_4_8')
btn9 = InlineKeyboardButton(text='📙 Тема №9 ОЧП',callback_data='menu_3_4_9')
btn10 = InlineKeyboardButton(text='📙 Тема №10 Обороты',callback_data='menu_3_4_10')
btn11 = InlineKeyboardButton(text='📙 Тема №11 Вводные',callback_data='menu_3_4_11')
btn12 = InlineKeyboardButton(text='📙 Тема №12 Запятые',callback_data='menu_3_4_12')
btn13 = InlineKeyboardButton(text='📙 Тема №13 Тире',callback_data='menu_3_4_13')
btn14 = InlineKeyboardButton(text='📙 Тема №14 Двоеточие',callback_data='menu_3_4_14')
btn15 = InlineKeyboardButton(text='📙 Какие повторить',callback_data='menu_3_4_15')
btn16 = InlineKeyboardButton(text='◀️ Назад',callback_data='back_to_menu_3')
menu_3_4.insert(btn1)
menu_3_4.insert(btn2)
menu_3_4.insert(btn3)
menu_3_4.insert(btn4)
menu_3_4.insert(btn5)
menu_3_4.insert(btn6)
menu_3_4.insert(btn7)
menu_3_4.insert(btn8)
menu_3_4.insert(btn9)
menu_3_4.insert(btn10)
menu_3_4.insert(btn11)
menu_3_4.insert(btn12)
menu_3_4.insert(btn13)
menu_3_4.insert(btn14)
menu_3_4.insert(btn15)
menu_3_4.insert(btn16)


menu_3_5 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='📘 №8 Синтаксис',callback_data='menu_3_5_1')
btn2 = InlineKeyboardButton(text='📘 №16 СПП,ОЧП,Односоставные',callback_data='menu_3_5_2')
btn3 = InlineKeyboardButton(text='📘 №17 Оборотные',callback_data='menu_3_5_3')
btn4 = InlineKeyboardButton(text='📘 №18 Вводные',callback_data='menu_3_5_4')
btn5 = InlineKeyboardButton(text='📘 №19 СПП-1',callback_data='menu_3_5_5')
btn6 = InlineKeyboardButton(text='📘 №20 СПП-2',callback_data='menu_3_5_6')
btn7 = InlineKeyboardButton(text='📘 №21 Запятые/Тире/Двоеточие',callback_data='menu_3_5_7')
btn8 = InlineKeyboardButton(text='📘 Какие повторить',callback_data='menu_3_5_8')
btn9 = InlineKeyboardButton(text='◀️ Назад',callback_data='back_to_menu_3')
menu_3_5.insert(btn1)
menu_3_5.insert(btn2)
menu_3_5.insert(btn3)
menu_3_5.insert(btn4)
menu_3_5.insert(btn5)
menu_3_5.insert(btn6)
menu_3_5.insert(btn7)
menu_3_5.insert(btn8)
menu_3_5.insert(btn9)

menu_3_6 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='📗 №3 Стилистика',callback_data='menu_3_6_1')
btn2 = InlineKeyboardButton(text='📗 №4 Ударение',callback_data='menu_3_6_2')
btn3 = InlineKeyboardButton(text='📗 №22 СХВ',callback_data='menu_3_6_3')
btn4 = InlineKeyboardButton(text='📗 №24 Типы речи',callback_data='menu_3_6_4')
btn8 = InlineKeyboardButton(text='📗 Какие повторить',callback_data='menu_3_6_5')
btn9 = InlineKeyboardButton(text='◀️ Назад',callback_data='back_to_menu_3')
menu_3_6.insert(btn1)
menu_3_6.insert(btn2)
menu_3_6.insert(btn3)
menu_3_6.insert(btn4)
menu_3_6.insert(btn5)
menu_3_6.insert(btn6)
menu_3_6.insert(btn7)
menu_3_6.insert(btn8)
menu_3_6.insert(btn9)

menu_4 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='📃 Статистика подборки',callback_data='menu_4_1')
btn2 = InlineKeyboardButton(text='🗄 Подборки',callback_data='menu_4_2')
btn3 = InlineKeyboardButton(text='◀️ Назад',callback_data='back_to_menu')
menu_4.insert(btn1)
menu_4.insert(btn2)
menu_4.insert(btn3)

menu_4_1 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='📓 По заданиям',callback_data='menu_4_1_1')
btn2 = InlineKeyboardButton(text='📔 Общая',callback_data='menu_4_1_2')
btn3 = InlineKeyboardButton(text='✨ Рейтинг',callback_data='menu_4_1_2')
btn4 = InlineKeyboardButton(text='◀️ Назад',callback_data='back_to_menu_4')
menu_4_1.insert(btn1)
menu_4_1.insert(btn2)
menu_4_1.insert(btn3)
menu_4_1.insert(btn4)

menu_4_1_1 = InlineKeyboardMarkup(row_width=7)
btn1 = InlineKeyboardButton(text='№1',callback_data='menu_4_1_1_1')
btn2 = InlineKeyboardButton(text='№2',callback_data='menu_4_1_1_2')
btn3 = InlineKeyboardButton(text='№3',callback_data='menu_4_1_1_3')
btn4 = InlineKeyboardButton(text='№4',callback_data='menu_4_1_1_4')
btn5 = InlineKeyboardButton(text='№5',callback_data='menu_4_1_1_5')
btn6 = InlineKeyboardButton(text='№6',callback_data='menu_4_1_1_6')
btn7 = InlineKeyboardButton(text='№7',callback_data='menu_4_1_1_7')
btn8 = InlineKeyboardButton(text='№8',callback_data='menu_4_1_1_8')
btn9 = InlineKeyboardButton(text='№9',callback_data='menu_4_1_1_9')
btn10 = InlineKeyboardButton(text='№10',callback_data='menu_4_1_1_10')
btn11 = InlineKeyboardButton(text='№11',callback_data='menu_4_1_1_11')
btn12 = InlineKeyboardButton(text='№12',callback_data='menu_4_1_1_12')
btn13 = InlineKeyboardButton(text='№13',callback_data='menu_4_1_1_13')
btn14 = InlineKeyboardButton(text='№14',callback_data='menu_4_1_1_14')
btn15 = InlineKeyboardButton(text='№15',callback_data='menu_4_1_1_15')
btn16 = InlineKeyboardButton(text='№16',callback_data='menu_4_1_1_16')
btn17 = InlineKeyboardButton(text='№17',callback_data='menu_4_1_1_17')
btn18 = InlineKeyboardButton(text='№18',callback_data='menu_4_1_1_18')
btn19 = InlineKeyboardButton(text='№19',callback_data='menu_4_1_1_19')
btn20 = InlineKeyboardButton(text='№20',callback_data='menu_4_1_1_20')
btn21 = InlineKeyboardButton(text='№21',callback_data='menu_4_1_1_21')
btn22 = InlineKeyboardButton(text='№22',callback_data='menu_4_1_1_22')
btn23 = InlineKeyboardButton(text='№23',callback_data='menu_4_1_1_23')
btn24 = InlineKeyboardButton(text='№24',callback_data='menu_4_1_1_24')
btn25 = InlineKeyboardButton(text='№25',callback_data='menu_4_1_1_25')
btn26 = InlineKeyboardButton(text='№26',callback_data='menu_4_1_1_26')
btn27 = InlineKeyboardButton(text='◀️ Назад',callback_data='back_to_menu_4_1')
menu_4_1_1.insert(btn1)
menu_4_1_1.insert(btn2)
menu_4_1_1.insert(btn3)
menu_4_1_1.insert(btn4)
menu_4_1_1.insert(btn5)
menu_4_1_1.insert(btn6)
menu_4_1_1.insert(btn7)
menu_4_1_1.insert(btn8)
menu_4_1_1.insert(btn9)
menu_4_1_1.insert(btn10)
menu_4_1_1.insert(btn11)
menu_4_1_1.insert(btn12)
menu_4_1_1.insert(btn13)
menu_4_1_1.insert(btn14)
menu_4_1_1.insert(btn15)
menu_4_1_1.insert(btn16)
menu_4_1_1.insert(btn17)
menu_4_1_1.insert(btn18)
menu_4_1_1.insert(btn19)
menu_4_1_1.insert(btn20)
menu_4_1_1.insert(btn21)
menu_4_1_1.insert(btn22)
menu_4_1_1.insert(btn23)
menu_4_1_1.insert(btn24)
menu_4_1_1.insert(btn25)
menu_4_1_1.insert(btn26)
menu_4_1_1.insert(btn27)

menu_4_2 = InlineKeyboardMarkup(row_width=7)
btn1 = InlineKeyboardButton(text='№1',callback_data='menu_4_2_1')
btn2 = InlineKeyboardButton(text='№2',callback_data='menu_4_2_2')
btn3 = InlineKeyboardButton(text='№3',callback_data='menu_4_2_3')
btn4 = InlineKeyboardButton(text='№4',callback_data='menu_4_2_4')
btn5 = InlineKeyboardButton(text='№5',callback_data='menu_4_2_5')
btn6 = InlineKeyboardButton(text='№6',callback_data='menu_4_2_6')
btn7 = InlineKeyboardButton(text='№7',callback_data='menu_4_2_7')
btn8 = InlineKeyboardButton(text='№8',callback_data='menu_4_2_8')
btn9 = InlineKeyboardButton(text='№9',callback_data='menu_4_2_9')
btn10 = InlineKeyboardButton(text='№10',callback_data='menu_4_2_10')
btn11 = InlineKeyboardButton(text='№11',callback_data='menu_4_2_11')
btn12 = InlineKeyboardButton(text='№12',callback_data='menu_4_2_12')
btn13 = InlineKeyboardButton(text='№13',callback_data='menu_4_2_13')
btn14 = InlineKeyboardButton(text='№14',callback_data='menu_4_2_14')
btn15 = InlineKeyboardButton(text='№15',callback_data='menu_4_2_15')
btn16 = InlineKeyboardButton(text='№16',callback_data='menu_4_2_16')
btn17 = InlineKeyboardButton(text='№17',callback_data='menu_4_2_17')
btn18 = InlineKeyboardButton(text='№18',callback_data='menu_4_2_18')
btn19 = InlineKeyboardButton(text='№19',callback_data='menu_4_2_19')
btn20 = InlineKeyboardButton(text='№20',callback_data='menu_4_2_20')
btn21 = InlineKeyboardButton(text='№21',callback_data='menu_4_2_21')
btn22 = InlineKeyboardButton(text='№22',callback_data='menu_4_2_22')
btn23 = InlineKeyboardButton(text='№23',callback_data='menu_4_2_23')
btn24 = InlineKeyboardButton(text='№24',callback_data='menu_4_2_24')
btn25 = InlineKeyboardButton(text='№25',callback_data='menu_4_2_25')
btn26 = InlineKeyboardButton(text='№26',callback_data='menu_4_2_26')
btn27 = InlineKeyboardButton(text='◀️ Назад',callback_data='back_to_menu_4')
menu_4_2.insert(btn1)
menu_4_2.insert(btn2)
menu_4_2.insert(btn3)
menu_4_2.insert(btn4)
menu_4_2.insert(btn5)
menu_4_2.insert(btn6)
menu_4_2.insert(btn7)
menu_4_2.insert(btn8)
menu_4_2.insert(btn9)
menu_4_2.insert(btn10)
menu_4_2.insert(btn11)
menu_4_2.insert(btn12)
menu_4_2.insert(btn13)
menu_4_2.insert(btn14)
menu_4_2.insert(btn15)
menu_4_2.insert(btn16)
menu_4_2.insert(btn17)
menu_4_2.insert(btn18)
menu_4_2.insert(btn19)
menu_4_2.insert(btn20)
menu_4_2.insert(btn21)
menu_4_2.insert(btn22)
menu_4_2.insert(btn23)
menu_4_2.insert(btn24)
menu_4_2.insert(btn25)
menu_4_2.insert(btn26)
menu_4_2.insert(btn27)

menu_4_2_1 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='▶️ Начать тест',callback_data='start_ask')
btn2 = InlineKeyboardButton(text='◀️ Назад',callback_data='back_to_menu_4_2')
menu_4_2_1.insert(btn1)
menu_4_2_1.insert(btn2)

menu_4_2_2 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='▶️ Начать тест',callback_data='start_ask')
btn2 = InlineKeyboardButton(text='◀️ Назад',callback_data='back_to_menu_4_2')
menu_4_2_2.insert(btn1)
menu_4_2_2.insert(btn2)

menu_4_2_3 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='▶️ Начать тест',callback_data='start_ask')
btn2 = InlineKeyboardButton(text='◀️ Назад',callback_data='back_to_menu_4_2')
menu_4_2_3.insert(btn1)
menu_4_2_3.insert(btn2)

menu_4_2_4 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='▶️ Начать тест',callback_data='start_ask')
btn2 = InlineKeyboardButton(text='◀️ Назад',callback_data='back_to_menu_4_2')
menu_4_2_4.insert(btn1)
menu_4_2_4.insert(btn2)

menu_4_2_5 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='▶️ Начать тест',callback_data='start_ask')
btn2 = InlineKeyboardButton(text='◀️ Назад',callback_data='back_to_menu_4_2')
menu_4_2_5.insert(btn1)
menu_4_2_5.insert(btn2)

menu_4_2_6 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='▶️ Начать тест',callback_data='start_ask')
btn2 = InlineKeyboardButton(text='◀️ Назад',callback_data='back_to_menu_4_2')
menu_4_2_6.insert(btn1)
menu_4_2_6.insert(btn2)

menu_4_2_7 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='▶️ Начать тест',callback_data='start_ask')
btn2 = InlineKeyboardButton(text='◀️ Назад',callback_data='back_to_menu_4_2')
menu_4_2_7.insert(btn1)
menu_4_2_7.insert(btn2)

menu_4_2_8 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='▶️ Начать тест',callback_data='start_ask')
btn2 = InlineKeyboardButton(text='◀️ Назад',callback_data='back_to_menu_4_2')
menu_4_2_8.insert(btn1)
menu_4_2_8.insert(btn2)

menu_4_2_9 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='▶️ Начать тест',callback_data='start_ask')
btn2 = InlineKeyboardButton(text='◀️ Назад',callback_data='back_to_menu_4_2')
menu_4_2_9.insert(btn1)
menu_4_2_9.insert(btn2)

menu_4_2_10 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='▶️ Начать тест',callback_data='start_ask')
btn2 = InlineKeyboardButton(text='◀️ Назад в меню',callback_data='back_to_menu_4_2')
menu_4_2_10.insert(btn1)
menu_4_2_10.insert(btn2)

menu_4_2_11 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='▶️ Начать тест',callback_data='start_ask')
btn2 = InlineKeyboardButton(text='◀️ Назад',callback_data='back_to_menu_4_2')
menu_4_2_11.insert(btn1)
menu_4_2_11.insert(btn2)

menu_4_2_12 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='▶️ Начать тест',callback_data='start_ask')
btn2 = InlineKeyboardButton(text='◀️ Назад в меню',callback_data='back_to_menu_4_2')
menu_4_2_12.insert(btn1)
menu_4_2_12.insert(btn2)

menu_4_2_13 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='▶️ Начать тест',callback_data='start_ask')
btn2 = InlineKeyboardButton(text='◀️ Назад',callback_data='back_to_menu_4_2')
menu_4_2_13.insert(btn1)
menu_4_2_13.insert(btn2)

menu_4_2_14 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='▶️ Начать тест',callback_data='start_ask')
btn2 = InlineKeyboardButton(text='◀️ Назад',callback_data='back_to_menu_4_2')
menu_4_2_14.insert(btn1)
menu_4_2_14.insert(btn2)

menu_4_2_15 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='▶️ Начать тест',callback_data='start_ask')
btn2 = InlineKeyboardButton(text='◀️ Назад',callback_data='back_to_menu_4_2')
menu_4_2_15.insert(btn1)
menu_4_2_15.insert(btn2)

menu_4_2_16 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='▶️ Начать тест',callback_data='start_ask')
btn2 = InlineKeyboardButton(text='◀️ Назад',callback_data='back_to_menu_4_2')
menu_4_2_16.insert(btn1)
menu_4_2_16.insert(btn2)

menu_4_2_17 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='▶️ Начать тест',callback_data='start_ask')
btn2 = InlineKeyboardButton(text='◀️ Назад',callback_data='back_to_menu_4_2')
menu_4_2_17.insert(btn1)
menu_4_2_17.insert(btn2)

menu_4_2_18 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='▶️ Начать тест',callback_data='start_ask')
btn2 = InlineKeyboardButton(text='◀️ Назад',callback_data='back_to_menu_4_2')
menu_4_2_18.insert(btn1)
menu_4_2_18.insert(btn2)

menu_4_2_19 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='▶️ Начать тест',callback_data='start_ask')
btn2 = InlineKeyboardButton(text='◀️ Назад',callback_data='back_to_menu_4_2')
menu_4_2_19.insert(btn1)
menu_4_2_19.insert(btn2)

menu_4_2_20 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='▶️ Начать тест',callback_data='start_ask')
btn2 = InlineKeyboardButton(text='◀️ Назад',callback_data='back_to_menu_4_2')
menu_4_2_20.insert(btn1)
menu_4_2_20.insert(btn2)

menu_4_2_21 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='▶️ Начать тест',callback_data='start_ask')
btn2 = InlineKeyboardButton(text='◀️ Назад',callback_data='back_to_menu_4_2')
menu_4_2_21.insert(btn1)
menu_4_2_21.insert(btn2)

menu_4_2_22 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='▶️ Начать тест',callback_data='start_ask')
btn2 = InlineKeyboardButton(text='◀️ Назад',callback_data='back_to_menu_4_2')
menu_4_2_22.insert(btn1)
menu_4_2_22.insert(btn2)

menu_4_2_23 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='▶️ Начать тест',callback_data='start_ask')
btn2 = InlineKeyboardButton(text='◀️ Назад',callback_data='back_to_menu_4_2')
menu_4_2_23.insert(btn1)
menu_4_2_23.insert(btn2)

menu_4_2_24 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='▶️ Начать тест',callback_data='start_ask')
btn2 = InlineKeyboardButton(text='◀️ Назад',callback_data='back_to_menu_4_2')
menu_4_2_24.insert(btn1)
menu_4_2_24.insert(btn2)

menu_4_2_25 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='▶️ Начать тест',callback_data='start_ask')
btn2 = InlineKeyboardButton(text='◀️ Назад',callback_data='back_to_menu_4_2')
menu_4_2_25.insert(btn1)
menu_4_2_25.insert(btn2)

menu_4_2_26 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='▶️ Начать тест',callback_data='start_ask')
btn2 = InlineKeyboardButton(text='◀️ Назад',callback_data='back_to_menu_4_2')
menu_4_2_26.insert(btn1)
menu_4_2_26.insert(btn2)

menu_4_2_1_1 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='🗄 Статистика',callback_data='rate')
btn2 = InlineKeyboardButton(text='📝 Еще тест',callback_data='menu_4_2_1_1_1')
btn3 = InlineKeyboardButton(text='◀️ Назад',callback_data='back_to_menu_4_2_1')
menu_4_2_1_1.insert(btn1)
menu_4_2_1_1.insert(btn2)
menu_4_2_1_1.insert(btn3)

calendar = InlineKeyboardMarkup(row_width=7)
btn1 = InlineKeyboardButton(text='1',callback_data='1')
btn2 = InlineKeyboardButton(text='2',callback_data='2')
btn3 = InlineKeyboardButton(text='3',callback_data='3')
btn4 = InlineKeyboardButton(text='4',callback_data='4')
btn5 = InlineKeyboardButton(text='5',callback_data='5')
btn6 = InlineKeyboardButton(text='6',callback_data='6')
btn7 = InlineKeyboardButton(text='7',callback_data='7')
btn8 = InlineKeyboardButton(text='8',callback_data='8')
btn9 = InlineKeyboardButton(text='9',callback_data='9')
btn10 = InlineKeyboardButton(text='10',callback_data='10')
btn11 = InlineKeyboardButton(text='11',callback_data='11')
btn12 = InlineKeyboardButton(text='12',callback_data='12')
btn13 = InlineKeyboardButton(text='13',callback_data='13')
btn14 = InlineKeyboardButton(text='14',callback_data='14')
btn15 = InlineKeyboardButton(text='15',callback_data='15')
btn16 = InlineKeyboardButton(text='16',callback_data='16')
btn17 = InlineKeyboardButton(text='17',callback_data='17')
btn18 = InlineKeyboardButton(text='18',callback_data='18')
btn19 = InlineKeyboardButton(text='19',callback_data='19')
btn20 = InlineKeyboardButton(text='20',callback_data='20')
btn21 = InlineKeyboardButton(text='21',callback_data='21')
btn22 = InlineKeyboardButton(text='22',callback_data='22')
btn23 = InlineKeyboardButton(text='23',callback_data='23')
btn24 = InlineKeyboardButton(text='24',callback_data='24')
btn25 = InlineKeyboardButton(text='25',callback_data='25')
btn26 = InlineKeyboardButton(text='26',callback_data='26')
btn27 = InlineKeyboardButton(text='27',callback_data='27')
btn28 = InlineKeyboardButton(text='28',callback_data='28')
btn29 = InlineKeyboardButton(text='◀️ Назад',callback_data='back_to_menu')
calendar.insert(btn1)
calendar.insert(btn2)
calendar.insert(btn3)
calendar.insert(btn4)
calendar.insert(btn5)
calendar.insert(btn6)
calendar.insert(btn7)
calendar.insert(btn8)
calendar.insert(btn9)
calendar.insert(btn10)
calendar.insert(btn11)
calendar.insert(btn12)
calendar.insert(btn13)
calendar.insert(btn14)
calendar.insert(btn15)
calendar.insert(btn16)
calendar.insert(btn17)
calendar.insert(btn18)
calendar.insert(btn19)
calendar.insert(btn20)
calendar.insert(btn21)
calendar.insert(btn22)
calendar.insert(btn23)
calendar.insert(btn24)
calendar.insert(btn25)
calendar.insert(btn26)
calendar.insert(btn27)
calendar.insert(btn28)
calendar.insert(btn29)


mount = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='Январь',callback_data='jan')
btn2 = InlineKeyboardButton(text='Февраль',callback_data='feb')
btn3 = InlineKeyboardButton(text='Март',callback_data='mar')
btn4 = InlineKeyboardButton(text='Апрель',callback_data='apr')
btn5 = InlineKeyboardButton(text='Май',callback_data='mai')
btn6 = InlineKeyboardButton(text='Июнь',callback_data='iun')
btn7 = InlineKeyboardButton(text='Июль',callback_data='iul')
btn8 = InlineKeyboardButton(text='Август',callback_data='avg')
btn9 = InlineKeyboardButton(text='Сентябрь',callback_data='sent')
btn10 = InlineKeyboardButton(text='Октябрь',callback_data='okt')
btn11 = InlineKeyboardButton(text='Ноябрь',callback_data='noyab')
btn12 = InlineKeyboardButton(text='Декабрь',callback_data='dec')
btn13 = InlineKeyboardButton(text='◀️ Назад',callback_data='back_to_menu')
mount.insert(btn1)
mount.insert(btn2)
mount.insert(btn3)
mount.insert(btn4)
mount.insert(btn5)
mount.insert(btn6)
mount.insert(btn7)
mount.insert(btn8)
mount.insert(btn9)
mount.insert(btn10)
mount.insert(btn11)
mount.insert(btn12)
mount.insert(btn13)

time = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='10:00',callback_data='10:00')
btn2 = InlineKeyboardButton(text='11:00',callback_data='11:00')
btn3 = InlineKeyboardButton(text='12:00',callback_data='12:00')
btn4 = InlineKeyboardButton(text='13:00',callback_data='13:00')
btn5 = InlineKeyboardButton(text='14:00',callback_data='14:00')
btn6 = InlineKeyboardButton(text='15:00',callback_data='15:00')
btn7 = InlineKeyboardButton(text='16:00',callback_data='16:00')
btn8 = InlineKeyboardButton(text='17:00',callback_data='17:00')
btn9 = InlineKeyboardButton(text='◀️ Назад',callback_data='back_to_menu')
time.insert(btn1)
time.insert(btn2)
time.insert(btn3)
time.insert(btn4)
time.insert(btn5)
time.insert(btn6)
time.insert(btn7)
time.insert(btn8)
time.insert(btn9)

mailing = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='📨 Включить\выключить рассылку',callback_data='off_on_mailing')
btn2 = InlineKeyboardButton(text='◀️ назад',callback_data='back_to_menu')
mailing.insert(btn1)
mailing.insert(btn2)

cancel = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='Отмена',callback_data='cancel')
cancel.insert(btn1)

social = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='Вконтакте',url='https://vk.com/museumskfu')
btn2 = InlineKeyboardButton(text='Instagram',url='https://www.instagram.com/museumskfu/')
btn3 = InlineKeyboardButton(text='Facebook',url='https://www.facebook.com/museumskfu/')
btn4 = InlineKeyboardButton(text='◀️ назад',callback_data='back_to_menu')
social.insert(btn1)
social.insert(btn2)
social.insert(btn3)
social.insert(btn4)

quiz1 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='Ответ',callback_data='otv11')
btn2 = InlineKeyboardButton(text='Ответ',callback_data='otv12')
btn3 = InlineKeyboardButton(text='Ответ',callback_data='otv13')
quiz1.insert(btn1)
quiz1.insert(btn2)
quiz1.insert(btn3)

quiz2 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='Ответ',callback_data='otv21')
btn2 = InlineKeyboardButton(text='Ответ',callback_data='otv22')
btn3 = InlineKeyboardButton(text='Ответ',callback_data='otv23')
quiz2.insert(btn1)
quiz2.insert(btn2)
quiz2.insert(btn3)

quiz3 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='Ответ',callback_data='otv31')
btn2 = InlineKeyboardButton(text='Ответ',callback_data='otv32')
btn3 = InlineKeyboardButton(text='Ответ',callback_data='otv33')
quiz3.insert(btn1)
quiz3.insert(btn2)
quiz3.insert(btn3)

quiz4 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='Ответ',callback_data='otv41')
btn2 = InlineKeyboardButton(text='Ответ',callback_data='otv42')
btn3 = InlineKeyboardButton(text='Ответ',callback_data='otv43')
quiz4.insert(btn1)
quiz4.insert(btn2)
quiz4.insert(btn3)

quiz5 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='Ответ',callback_data='otv51')
btn2 = InlineKeyboardButton(text='Ответ',callback_data='otv52')
btn3 = InlineKeyboardButton(text='Ответ',callback_data='otv53')
quiz5.insert(btn1)
quiz5.insert(btn2)
quiz5.insert(btn3)

quiz6 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='Ответ',callback_data='otv61')
btn2 = InlineKeyboardButton(text='Ответ',callback_data='otv62')
btn3 = InlineKeyboardButton(text='Ответ',callback_data='otv63')
quiz6.insert(btn1)
quiz6.insert(btn2)
quiz6.insert(btn3)

quiz7 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='Ответ',callback_data='otv71')
btn2 = InlineKeyboardButton(text='Ответ',callback_data='otv72')
btn3 = InlineKeyboardButton(text='Ответ',callback_data='otv73')
quiz7.insert(btn1)
quiz7.insert(btn2)
quiz7.insert(btn3)